apiVersion: v1
kind: Service
metadata:
  name: haylugar-backend-service
spec:
  type: NodePort
  selector:
    app: haylugar-backend-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      name: http